config/routes.rb
FamilyNetwork::Application.routes.draw do

  resources :profiles

  devise_for :users, :path => "", :controllers => { :registrations => 'users/registrations'}, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => '', :sign_up => 'users/registrations' }

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
  end

  resources :ingredient_assignments

  resources :tool_assignments

  resources :ingredients

  resources :tools

  resources :recipes

  get "admin" => 'admin#index'

  root :to => 'dashboard#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'text_field'
  .control-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'text_field'
  .control-group
    = f.label :about, :class => 'control-label'
    .controls
      = f.text_field :about, :class => 'text_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), profiles_path, :class => 'btn'

app/views/profiles/edit.html.haml
- model_class = @profile.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/profiles/index.html.haml
- model_class = Profile.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:first_name)
      %th= model_class.human_attribute_name(:last_name)
      %th= model_class.human_attribute_name(:about)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @profiles.each do |profile|
      %tr
        %td= link_to profile.id, profile_path(profile)
        %td= profile.first_name
        %td= profile.last_name
        %td= profile.about
        %td= profile.user_id
        %td=l profile.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_profile_path(profile), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), profile_path(profile), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_profile_path, :class => 'btn btn-primary'

app/views/profiles/new.html.haml
- model_class = @profile.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/profiles/show.html.haml
- model_class = @profile.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @profile.first_name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @profile.last_name
%p
  %strong= model_class.human_attribute_name(:about) + ':'
  %br
  = @profile.about
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @profile.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), profiles_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_profile_path(@profile), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), profile_path(@profile), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'