config/routes.rb
FamilyNetwork::Application.routes.draw do

  resources :profiles

  devise_for :users, :path => "", :controllers => { :registrations => 'users/registrations'}, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => '', :sign_up => 'users/registrations' }

  devise_scope :user do
    get "logout", :to => "devise/sessions#destroy"
  end

  resources :ingredient_assignments

  resources :tool_assignments

  resources :ingredients

  resources :tools

  resources :recipes

  get "admin" => 'admin#index'

  root :to => 'dashboard#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredient_assignments, :dependent => :destroy
  has_many :ingredients, through: :ingredient_assignments
  has_many :tool_assignments, :dependent => :destroy
  has_many :tools, through: :tool_assignments
  has_many :steps, :dependent => :destroy

  belongs_to :user

  accepts_nested_attributes_for :tools
  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :steps, :allow_destroy => true
  accepts_nested_attributes_for :ingredient_assignments, :allow_destroy => true
  accepts_nested_attributes_for :tool_assignments, :allow_destroy => true
  
  validates_presence_of :title
 end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    # Add one default ingredient field
    # @recipe.ingredient_assignments.build.build_ingredient

    # Add one default tool field
    # @recipe.tool_assignments.build.build_tool

    # Add one default step field
    @recipe.steps.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    # Associate a user with this recipe
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.haml
= content_for :sidebar , render(template: 'recipes/show')
.row-fluid
  = form_for(@recipe) do |f|
    - if @recipe.errors.any?
      #error_explanation
        %h2
          = pluralize(@recipe.errors.count, "error") 
          prohibited this recipe from being saved:
        %ul
          - @recipe.errors.full_messages.each do |msg|
            %li= msg
    .span3
      .control-group
        = f.label :title, :class => 'control-label'
        .controls
          = f.text_field :title, :class => 'text_field'

      .control-group
        = f.label :description, :class => 'control-label'
        .controls
          = f.text_area :description, :class => 'text_area'
    .span6 
      %fieldset.tools
        %legend Tools:
        = render "tool_slug"
        = f.fields_for(:tool_assignments) do |builder|
          = render "tool_assignment_fields", :f => builder
        = link_to_add_fields "Add Tool", f, :tool_assignments
      
      %fieldset.ingredients
        %legend Ingredients:
        = render "ingredient_slug"
        = f.fields_for(:ingredient_assignments) do |builder|
          = render "ingredient_assignment_fields", :f => builder
        = link_to_add_fields 'Add Ingredient', f, :ingredient_assignments

      %fieldset.steps
        %legend Steps:
        = render "step_slug"
        = f.fields_for(:steps) do |builder|
          = render "step_fields", :f => builder
        = link_to_add_fields "Add Step", f, :steps
      
        = content_for :actions, f.submit(nil, :class => 'btn btn-primary', :id => 'recipe-submit')

app/views/recipes/_ingredient_assignment_fields.html.haml
.fields
  = f.hidden_field(:whole)
  = f.hidden_field(:numerator)
  = f.hidden_field(:denominator)
  = f.hidden_field(:unit)
  = f.fields_for :ingredient do |builder|
    = builder.hidden_field :title
    = f.hidden_field(:_destroy)

app/views/recipes/_ingredient_slug.html.haml
#ingredient-slugs.slug-fields
  .span12.whole
    = label :whole, "Measurement"
    = select_tag(:whole, options_for_select((1..15).to_a), include_blank: true)
  .span12.fraction
    = select_tag(:numerator, options_for_select((1..16).to_a), include_blank: true) 
    %span / 
    = select_tag(:denominator, options_for_select((1..16).to_a), include_blank: true)
  .span12.unit
    = select_tag(:unit, options_for_select(['tsp', 'Tbsp', 'c', 'lb', 'oz', 'Pt', 'Qt', 'Gal']))
  .span12.title
    = label :title, "Ingredient"
    = text_field_tag :title

app/views/recipes/_step_fields.html.haml
.fields
  = f.hidden_field(:description)
  = f.hidden_field(:_destroy)

app/views/recipes/_step_slug.html.haml
#step-slugs.slug-fields
  .span12.description
    = label_tag :description, 'Step Description'
    = text_area_tag :description

app/views/recipes/_tool_assignment_fields.html.haml
.fields
  = f.hidden_field(:count)
  = f.fields_for :tool do |builder|
    = builder.hidden_field :title
    = f.hidden_field(:_destroy)

app/views/recipes/_tool_fields.html.haml
.title
  = f.label :title, "Title"
  %br
  = f.text_area :title, :rows => 3
  %br
  = f.check_box :_destroy
  = f.label :_destroy, "Remove Title"

app/views/recipes/_tool_slug.html.haml
#tool-slugs.slug-fields
  .span4.tool-count
    = label :count, "Count"
    = select_tag(:count, options_for_select((1..15).to_a))
  .span4.tool-input
    = label :title, "Tool"
    = text_field_tag :title

app/views/recipes/edit.html.haml
%h1 Editing recipe

= render 'form'
= content_for :action_links, (link_to('Show', @recipe, class: 'btn') + ' ' + link_to('Dashboard', root_path, class: 'btn'))

app/views/recipes/index.html.haml
- model_class = Recipe.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:title)
      %th=t '.actions', :default => t("helpers.actions")

  %tbody
    - @recipes.each do |recipe|
      %tr
        %td= link_to recipe.title, recipe_path(recipe)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_recipe_path(recipe), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), recipe_path(recipe), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_recipe_path, :class => 'btn btn-primary'

app/views/recipes/new.html.haml
%h1 New recipe

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
#recipe
  .title
    %b Title:
    - if @recipe.title.present?
      = @recipe.title

  .description
    %b Description:
    - if @recipe.description.present?
      = @recipe.description

  .tools
    %b Tools:
    %ul
      - if @recipe.tool_assignments.present?
        - @recipe.tool_assignments.each_with_index do |ta, i|
          %li
            = ta.count
            = ta.tool.title
            = link_to_remove("tool-#{i}")

  .ingredients
    %b Ingredients:
    %ul
      - if @recipe.ingredient_assignments.present?
        - @recipe.ingredient_assignments.each_with_index do |ia, i|
          %li
            = "#{ia.whole} #{ia.numerator.to_s} / #{ia.denominator.to_s}#{ia.unit} #{ia.ingredient.title}"
            = link_to_remove("ingredient-#{i}")

  .steps
    %b Steps:
    %ol
      - if @recipe.steps.present?
        - @recipe.steps.each_with_index do |s, i|
          %li
            = s.description
            = link_to_remove("step-#{i}")

- if params[:action] == 'show'
  = content_for :action_links, (link_to('Edit', edit_recipe_path(@recipe), class: 'btn') + ' ' + link_to('Dashboard', root_path, class: 'btn'))